### ISSUE TITLE
Update OZ version to latest

### ISSUE THREAD

**Issue by MerlinEgalite** [MerlinEgalite/universal-rewards-distributor#10]
https://twitter.com/openzeppelin/status/1669816616157319168?s=46&t=OMCcEUE0MTz3vvvH9kIj4g

**Comment by obatirou** [comment]
Hi @MerlinEgalite 👋 
Made a PR to update to 4.9.2 [here](https://github.com/MerlinEgalite/universal-rewards-distributor/pull/11)

**Comment by MerlinEgalite** [comment]
Awesome looking at it rn!
