### ISSUE TITLE
Implement missing tests

### ISSUE THREAD

**Issue by MerlinEgalite** [MerlinEgalite/universal-rewards-distributor#2]
- [ ] events
- [ ] claimed getter

**Comment by obatirou** [comment]
Would be happy to contribute if ok for you

The 2 tasks seem straightforward but I have a doubt on how to implement the test for the `RewardsClaimed` event.
*  A simple solution would be to add an `expectEvent` in `_claimAndVerifyRewards` for each call to `claim` function. But it would hide the `expectEvent` in an internal function which would not be ideal imo.
*  Other solution would be to create a new simpler test on the base of `testRewards` but only `claim` for one user and not verify rewards maybe. But seems redondant and not necessary.

I would tend to the first one but maybe there are other solutions I miss ?
What are your thoughts on this ?
Once cleared, I could hop on the implementation if you want

**Comment by MerlinEgalite** [comment]
Hi @obatirou!

Let's do 1 and avoid code redundancy. If later we want to change the event or whatever there's only one place to change so it's much more maintainable.

And super happy that you can contribute! 🔥

**Comment by obatirou** [comment]
Fine for me, let's do 1 !
Here is the implementation: https://github.com/MerlinEgalite/universal-rewards-distributor/pull/6

Also maybe it would be interesting to add the `claimed` getter to the interface ?
With something like
```solidity
 /* VIEW */
 function claimed(address account, address reward) external view returns (uint256);
```

I would say it should be in an other PR though

**Comment by MerlinEgalite** [comment]
Nice!

Hmm the state variable is already public so the getter is already present on the interface.

**Comment by obatirou** [comment]
Should have specified it is only a suggestion and personal preference for the getter, sorry for the confusion.
I like the pattern to have explicit getters in interfaces like in `Uniswap` or `Primitive Portfolio`. But only a suggestion.
