### ISSUE TITLE
Openzeppelin merkle-tree lib compatibility

### ISSUE THREAD

**Issue by obatirou** [MerlinEgalite/universal-rewards-distributor#8]
As is, if I am not mistaken, this contract is not compatible with the [Merkle-tree lib from OZ](https://github.com/OpenZeppelin/merkle-tree) as the leaves would need to be [double-hashed](https://github.com/OpenZeppelin/merkle-tree#standard-merkle-trees). From my understanding it is compatible with [merklejs](https://github.com/merkletreejs/merkletreejs) or other libs but might be vulnerable to second pre-image attacks or forgery attacks (see [notes](https://github.com/merkletreejs/merkletreejs#notes)) if not handled correctly. `merkletreejs` suggest to use OpenZeppelin lib when integrating with OpenZeppelin contracts.

The changes should be simple. 
It would require to change the hashing 
```solidity
// from
keccak256(abi.encodePacked(account, reward, claimable))))
// to
keccak256(bytes.concat(keccak256(abi.encode(account, reward, claimable))));
```

What are your thoughts on adding compatibility for OZ lib ?

**Comment by MerlinEgalite** [comment]
Yes I totally agree this is very misleading to use OZ for verifying but not their libraries to generate trees. I agree that we can make it compatible. I would also add a comment in the README to warn users to use OZ js lib to compute the tree instead of another library.

Thx for raising this!

**Comment by obatirou** [comment]
Great ! Thank you for confirming this.
Will work on a proposition and open a PR shortly
